//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSProjectNormalizer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Resource : global::System.Configuration.ApplicationSettingsBase {
        
        private static Resource defaultInstance = ((Resource)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Resource())));
        
        public static Resource Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(SolutionDir)artifacts\\$(Configuration)\\{ProjectType}\\$(AssemblyName)$(PlatformP" +
            "ath)")]
        public string SOLUTION_BUILD_FOLDER {
            get {
                return ((string)(this["SOLUTION_BUILD_FOLDER"]));
            }
            set {
                this["SOLUTION_BUILD_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(SolutionDir)obj\\$(Configuration)\\$(AssemblyName)$(PlatformPath)")]
        public string SOLUTION_INTERMEDIATE_FOLDER {
            get {
                return ((string)(this["SOLUTION_INTERMEDIATE_FOLDER"]));
            }
            set {
                this["SOLUTION_INTERMEDIATE_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!artifacts\\$(Configuration)$(PlatformPath)")]
        public string PROJECT_BUILD_FOLDER {
            get {
                return ((string)(this["PROJECT_BUILD_FOLDER"]));
            }
            set {
                this["PROJECT_BUILD_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!obj\\$(Configuration)$(PlatformPath)")]
        public string PROJECT_INTERMEDIATE_FOLDER {
            get {
                return ((string)(this["PROJECT_INTERMEDIATE_FOLDER"]));
            }
            set {
                this["PROJECT_INTERMEDIATE_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(SolutionDir)Build\\\\common.props")]
        public string SOLUTIONDIR_BUILD_COMMON_PROPS {
            get {
                return ((string)(this["SOLUTIONDIR_BUILD_COMMON_PROPS"]));
            }
            set {
                this["SOLUTIONDIR_BUILD_COMMON_PROPS"] = value;
            }
        }
    }
}
