//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSProjectNormalizer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Resource : global::System.Configuration.ApplicationSettingsBase {
        
        private static Resource defaultInstance = ((Resource)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Resource())));
        
        public static Resource Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BUILD_DIR {
            get {
                return ((string)(this["BUILD_DIR"]));
            }
            set {
                this["BUILD_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TEST_OUTPUT_PATH {
            get {
                return ((string)(this["TEST_OUTPUT_PATH"]));
            }
            set {
                this["TEST_OUTPUT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BIN_OUTPUT_PATH {
            get {
                return ((string)(this["BIN_OUTPUT_PATH"]));
            }
            set {
                this["BIN_OUTPUT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string INTERMEDIATE_OUTPUT_PATH {
            get {
                return ((string)(this["INTERMEDIATE_OUTPUT_PATH"]));
            }
            set {
                this["INTERMEDIATE_OUTPUT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACCEPTANCE_TEST_OUTPUT_PATH {
            get {
                return ((string)(this["ACCEPTANCE_TEST_OUTPUT_PATH"]));
            }
            set {
                this["ACCEPTANCE_TEST_OUTPUT_PATH"] = value;
            }
        }
    }
}
